/**
 * Text to Image Font 生成器配置
 * 包含所有可以生成图片的字体生成器信息
 */

export interface TextToImageFontConfig {
  id: string;
  name: string; // 显示名称
  path: string; // 路由路径（不含 locale）
  fontName: string; // 字体名称（用于加载）
  fontFile: string; // 字体文件路径
  previewText: string; // 预览文本
  defaultColor: string; // 默认颜色
  defaultBgColor?: string; // 默认背景色
  category?: string; // 分类
}

export const TEXT_TO_IMAGE_FONTS: TextToImageFontConfig[] = [
  {
    id: "carly-rae-jepsen",
    name: "Carly Rae Jepsen Font",
    path: "/carly-rae-jepsen-font",
    fontName: "ColorsOfAutumn",
    fontFile: "/Colors-Of-Autumn/Colors-Of-Autumn-1.ttf",
    previewText: "E•MO•TION",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Music",
  },
  {
    id: "pokemon",
    name: "Pokemon Font",
    path: "/pokemon-font",
    fontName: "PokemonSolid",
    fontFile: "/Pokemon/Pokemon-Solid-2.ttf",
    previewText: "POKEMON",
    defaultColor: "#FFD700",
    defaultBgColor: "#000000",
    category: "Gaming",
  },
  {
    id: "minecraft",
    name: "Minecraft Font",
    path: "/minecraft-font",
    fontName: "Minecraft",
    fontFile: "/Minecraft/Minecraft-1.ttf",
    previewText: "MINECRAFT",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Gaming",
  },
  {
    id: "disney",
    name: "Disney Font",
    path: "/disney-font",
    fontName: "Waltograph42",
    fontFile: "/Waltograph/waltograph42-1.otf",
    previewText: "DISNEY",
    defaultColor: "#0066FF",
    defaultBgColor: "#000000",
    category: "Brand",
  },
  {
    id: "brat",
    name: "Brat Font",
    path: "/brat-font",
    fontName: "ArialNarrow",
    fontFile: "/Arial-Narrow/arial-narrow-7-1.ttf",
    previewText: "BRAT",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Music",
  },
  {
    id: "the-life-of-a-showgirl",
    name: "The Life of a Showgirl Font",
    path: "/the-life-of-a-showgirl-font",
    fontName: "SteelfishBdIt",
    fontFile: "/steelfish/Steelfish Bd It.otf",
    previewText: "THE LIFE OF A SHOWGIRL",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Music",
  },
  {
    id: "calligraphy",
    name: "Calligraphy Generator",
    path: "/calligraphy-generator",
    fontName: "ArizoniaRegular",
    fontFile: "/Arizonia-Regular/Arizonia-Regular-OTF.otf",
    previewText: "Calligraphy",
    defaultColor: "#10b981",
    defaultBgColor: "#ffffff",
    category: "Style",
  },
  {
    id: "graffiti",
    name: "Graffiti Generator",
    path: "/graffiti-generator",
    fontName: "Cancontrol",
    fontFile: "/Cancontrol/Cancontrol/cancontrol-1.ttf",
    previewText: "GRAFFITI",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Style",
  },
  {
    id: "hindi",
    name: "Hindi Font Generator",
    path: "/hindi-font-generator",
    fontName: "AmsAaditya",
    fontFile: "/Tillana/Ams Aaditya.ttf",
    previewText: "हिन्दी",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Language",
  },
  {
    id: "tamil",
    name: "Tamil Font Generator",
    path: "/tamil-font-generator",
    fontName: "BaminiTamil",
    fontFile: "/Tamil/Bamini_Tamil.ttf",
    previewText: "தமிழ்",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Language",
  },
  {
    id: "malayalam",
    name: "Malayalam Font Generator",
    path: "/malayalam-font-generator",
    fontName: "MLTTAmbiliNormal",
    fontFile: "/ML-TTAmbili Normal/ML-TTAmbili Normal.ttf",
    previewText: "മലയാളം",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Language",
  },
  {
    id: "undertale",
    name: "Undertale Font",
    path: "/undertale-font",
    fontName: "MonsterFriendBack",
    fontFile: "/Undertale Font/MonsterFriendBack.otf",
    previewText: "UNDERTALE",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Gaming",
  },
  {
    id: "coca-cola",
    name: "Coca-Cola Font",
    path: "/coca-cola-font",
    fontName: "CocaColaII",
    fontFile: "/Coca_Cola/cocacolaii.ttf",
    previewText: "COCA-COLA",
    defaultColor: "#FF0000",
    defaultBgColor: "#ffffff",
    category: "Brand",
  },
  {
    id: "demon-slayer",
    name: "Demon Slayer Font",
    path: "/demon-slayer-font",
    fontName: "BloodCrow",
    fontFile: "/demon-slayer-font/bloodcrow.ttf",
    previewText: "DEMON SLAYER",
    defaultColor: "#FF0000",
    defaultBgColor: "#000000",
    category: "Anime",
  },
  {
    id: "gta",
    name: "GTA Font",
    path: "/gta-font",
    fontName: "Powerhouse",
    fontFile: "/grand-theft-auto/Powerhouse.ttf",
    previewText: "GTA",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Gaming",
  },
  {
    id: "squid-game",
    name: "Squid Game Font",
    path: "/squid-game-font",
    fontName: "GameOfSquids",
    fontFile: "/game-of-squids/GameOfSquids-1GMVL.ttf",
    previewText: "SQUID GAME",
    defaultColor: "#FFD700",
    defaultBgColor: "#000000",
    category: "Entertainment",
  },
  {
    id: "montserrat",
    name: "Montserrat Font",
    path: "/montserrat-font",
    fontName: "MontserratRegular",
    fontFile: "/Montserrat/Montserrat-Regular-8.otf",
    previewText: "MONTSERRAT",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Typography",
  },
  {
    id: "sonic",
    name: "Sonic Font",
    path: "/sonic-font",
    fontName: "NiseSegaSonic",
    fontFile: "/Nise-Sega-Sonic-Font/NiseSegaSonic.TTF",
    previewText: "SONIC",
    defaultColor: "#0066FF",
    defaultBgColor: "#000000",
    category: "Gaming",
  },
  {
    id: "plus-jakarta-sans",
    name: "Plus Jakarta Sans",
    path: "/plus-jakarta-sans",
    fontName: "PlusJakartaTextRegular",
    fontFile: "/plus-jakarta-sans/PlusJakartaText-Regular.otf",
    previewText: "PLUS JAKARTA",
    defaultColor: "#10b981",
    defaultBgColor: "#000000",
    category: "Typography",
  },
];


